package com.example.security

import android.util.Log
import com.example.BuildConfig

/**
 * Secure API Key management strategy for CardsApp.
 * Accesses API keys via BuildConfig generated by Secrets Gradle Plugin (.env file).
 * Never hardcodes secrets in application source code.
 */
object ApiKeyManager {
    private const val TAG = "ApiKeyManager"

    /**
     * Retrieves the Gemini / Cloud Vision API Key securely configured in runtime build parameters.
     */
    fun getGeminiApiKey(): String {
        return try {
            BuildConfig.GEMINI_API_KEY
        } catch (e: Exception) {
            Log.w(TAG, "GEMINI_API_KEY not found in BuildConfig", e)
            ""
        }
    }

    /**
     * Validates if a usable, non-placeholder API key is available for cloud operations.
     */
    fun hasValidCloudKey(): Boolean {
        val key = getGeminiApiKey().trim()
        val isValid = key.isNotEmpty() &&
                key != "MY_GEMINI_API_KEY" &&
                key != "YOUR_GEMINI_API_KEY" &&
                !key.startsWith("MY_")
        
        if (!isValid) {
            Log.d(TAG, "Cloud API Key is missing or placeholder. Switching to on-device OCR fallback.")
        }
        return isValid
    }
}
